version: "3.8"
services:
  spring-petclinic-rest:
    container_name: spring-petclinic-rest
    image: raihan95/spring-petclinic-rest:latest
    build: ./spring-petclinic-rest-master
    ports:
    - target: 9966
      published: 9966
      protocol: tcp

  spring-petclinic-angular:
    container_name: spring-petclinic-angular
    image: raihan95/spring-petclinic-angular:latest
    build: ./spring-petclinic-angular-master
    ports:
    - target: 8080
      published: 80
      protocol: tcp

